// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pollit.Application.Polls.GetPollFeed;
using Pollit.Domain.Users;
using Pollit.Infra.EfCore.NpgSql;

#nullable disable

namespace Pollit.Infra.SqlServer.Migrations
{
    [DbContext(typeof(PollitDbContext))]
    [Migration("20230715192212_PollResultsRawItems")]
    partial class PollResultsRawItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pollit.Application.Polls.GetPollFeed.GetPollFeedQueryResultItem", b =>
                {
                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasMyVote")
                        .HasColumnType("boolean");

                    b.Property<GetPollFeedQueryResultItemOption[]>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<double>("SearchRank")
                        .HasColumnType("double precision");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalVotesCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PollId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Comments.CommentVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("VoterId");

                    b.ToTable("Comments.Votes", (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Polls.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("character varying(125)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Polls", (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Polls.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PollId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("Polls.Options", (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Polls.PollOptionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PollOptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PollOptionId");

                    b.HasIndex("VoterId");

                    b.ToTable("Polls.Options.Votes", (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Users.ResetPasswordLinks.ResetPasswordLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ForcedExpiryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Users.ResetPasswordLinks", (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid ()");

                    b.Property<string>("Birthdate")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("EmailVerificationToken")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<GoogleProfileDto>("GoogleProfile")
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasTemporaryUserName")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserName");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Pollit.Infra.EfCore.NpgSql.Projections.Comments.GetCommentsOfAPollRawResultItem", b =>
                {
                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<int>("DownVotesCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MyVoteDirection")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<int>("UpVotesCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Pollit.Infra.EfCore.NpgSql.Projections.Polls.PollResultsRawItem", b =>
                {
                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntervalLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("OptionTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VotesCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Pollit.Domain.Comments.CommentVote", b =>
                {
                    b.HasOne("Pollit.Domain.Comments.Comment", null)
                        .WithMany("Votes")
                        .HasForeignKey("CommentId");
                });

            modelBuilder.Entity("Pollit.Domain.Polls.PollOption", b =>
                {
                    b.HasOne("Pollit.Domain.Polls.Poll", null)
                        .WithMany("Options")
                        .HasForeignKey("PollId");
                });

            modelBuilder.Entity("Pollit.Domain.Polls.PollOptionVote", b =>
                {
                    b.HasOne("Pollit.Domain.Polls.PollOption", null)
                        .WithMany("Votes")
                        .HasForeignKey("PollOptionId");
                });

            modelBuilder.Entity("Pollit.Domain.Users.ResetPasswordLinks.ResetPasswordLink", b =>
                {
                    b.HasOne("Pollit.Domain.Users.User", null)
                        .WithMany("ResetPasswordLinks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Pollit.Domain.Comments.Comment", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Pollit.Domain.Polls.Poll", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Pollit.Domain.Polls.PollOption", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Pollit.Domain.Users.User", b =>
                {
                    b.Navigation("ResetPasswordLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
